{{- $store := (input "developmentStore") -}}
{{- $fossilizers := (input "developmentFossilizer") -}}
{{- $require_tmstore := (or (eq $store "filetmpop") (eq $store "dummytmpop") (eq $store "postgrestmpop") (eq $store "rethinktmpop")) -}}
version: '2'
services:
  agentui:
    image: {{.agentui}}
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    - ./config/dev.env
    - ./config/dev.secret.env
    ports:
    - "4000:4000"
{{- if $require_tmstore }}
  indigoexplorer:
    image: {{.indigoexplorer}}
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    - ./config/dev.env
    - ./config/dev.secret.env
    ports:
    - "8000:4000"
{{- end}}
  agent:
    build:
      dockerfile: Dockerfile.dev
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
    ports:
    - "3000:3000"
  store:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
{{- if eq $store "filestore" }}
    user: root
    volumes:
    - ./segments:/var/stratumn/filestore
{{- end}}
{{- if eq $store "fabricstore" }}
  peer0.org1.example.com:
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE={{input "name"}}dev_default
{{- end}}
{{- if eq $store "postgresstore" }}
  postgres:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
{{- end}}
{{- if eq $store "rethinkstore" }}
  rethinkdb:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
{{- end}}
{{- if $require_tmstore }}
  tmnode:
    user: root
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
    ports:
    - "46656-46657:46656-46657"
    volumes:
    - ./tendermint:/data/tendermint
{{- if eq $store "filetmstore" }}
    - ./segments:/var/stratumn/filestore
{{- end}}
{{- end}}
{{- range $i, $fossilizer := $fossilizers}}
  {{$fossilizer}}:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
    ports:
    - "{{(add 6000 $i)}}"
{{- end}}
networks:
  default:
    driver: bridge
    driver_opts:
        name: {{input "name"}}_dev
