{{- with $store := (input "developmentStore") -}}
{{- with $fossilizer := (input "developmentFossilizer") -}}
version: '2'
services:
  agent:
    build:
      context: .
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    volumes:
    - .:/src/server
    depends_on:
    - store
    - fossilizer
  store:
    image: {{$store}}
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
{{- if eq $store "stratumn/postgresstore" }}
    depends_on:
    - postgres
{{- end}}
{{- if eq $store "stratumn/rethinkstore" }}
    depends_on:
    - rethinkdb
{{- end}}
{{- if eq $store "stratumn/postgresstore" }}
  postgres:
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    image: postgres
{{- end}}
{{- if eq $store "stratumn/rethinkstore" }}
  rethinkdb:
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    image: rethinkdb
{{- end}}
  fossilizer:
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    image: {{$fossilizer}}
{{- end}}
{{- end}}
