{{- with $store := (input "developmentStore") -}}
version: '2'
services:
  ui:
    image: stratumn/agent-ui:0.2.0
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    - ./config/dev.env
    - ./config/dev.secret.env
    ports:
    - "4000:4000"
    depends_on:
    - agent
  agent:
    build:
      dockerfile: Dockerfile.dev
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
    ports:
    - "3000:3000"
  store:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
{{- if eq $store "stratumn/filestore" }}
    volumes:
    - ./segments:/var/filestore
{{- end}}
{{- if eq $store "stratumn/postgresstore" }}
  postgres:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
    volumes:
    - postgres:/var/lib/postgresql/data
{{- end}}
{{- if eq $store "stratumn/rethinkstore" }}
  rethinkdb:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
    volumes:
    - rethinkdb:/data
{{- end}}
  fossilizer:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
{{- if eq $store "stratumn/postgresstore" }}
volumes:
  postgres:
    driver: local
{{- end}}
{{- if eq $store "stratumn/rethinkstore" }}
volumes:
  rethinkdb:
    driver: local
{{- end}}
networks:
  default:
    driver: bridge
    driver_opts:
        name: {{input "name"}}_dev
{{- end}}
