{{- $store := (input "developmentStore") -}}
{{- $fossilizer := (input "developmentFossilizer") -}}
version: '2'
services:
  agent:
    build:
      context: ./agent
    image: {{.dockerorg}}/{{.name}}-agent-js
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    volumes:
    - ./agent:/src/server
    depends_on:
    - store
    - fossilizer
  store:
    image: {{index . $store}}
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
{{- if eq $store "postgresstore" }}
    depends_on:
    - postgres
{{- end}}
{{- if eq $store "rethinkstore" }}
    depends_on:
    - rethinkdb
{{- end}}
{{- if eq $store "postgresstore" }}
  postgres:
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    image: {{.postgres}}
{{- end}}
{{- if eq $store "rethinkstore" }}
  rethinkdb:
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    image: {{.rethink}}
{{- end}}
  fossilizer:
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    image: {{index . $fossilizer}}
