{{- $store := (input "developmentStore") -}}
{{- $fossilizers := (input "developmentFossilizer") -}}
{{- $require_tmstore := (eq $store "tmstore") -}}
{{- $require_postgresql := (eq $store "postgresstore") -}}
{{- $require_rethinkdb := (eq $store "rethinkstore") -}}
{{- $require_couchdb := (eq $store "couchstore") -}}
version: '3'
services:
  agent:
    build:
      dockerfile: Dockerfile.test
    env_file:
    - ./config/test.env
    - ./config/test.secret.env
  store:
    env_file:
    - ./config/test.env
    - ./config/test.secret.env
{{- /* Ugly if cascade and DRY */}}
{{- /* https://github.com/stratumn/generators/issues/31 */}}
{{- if $require_postgresql }}
  postgres:
    env_file:
    - ./config/test.env
    - ./config/test.secret.env
{{- else if $require_tmstore }}
{{- if eq (input "tmpopUnderlyingStore") "postgrestmpop" }}
  postgres:
    env_file:
    - ./config/test.env
    - ./config/test.secret.env
{{- end}}
{{- end}}
{{- if $require_rethinkdb }}
  rethinkdb:
    env_file:
    - ./config/test.env
    - ./config/test.secret.env
{{- else if $require_tmstore }}
{{- if eq (input "tmpopUnderlyingStore") "rethinktmpop" }}
  rethinkdb:
    env_file:
    - ./config/test.env
    - ./config/test.secret.env
{{- end}}
{{- end}}
{{- /* End of ugly if cascade and DRY */}}
{{- if $require_couchdb }}
  couchdb:
    env_file:
    - ./config/test.env
    - ./config/test.secret.env
{{- end}}
{{- if $require_tmstore }}
  tmnode:
    user: root
    env_file:
    - ./config/test.env
    - ./config/test.secret.env
    volumes:
    - ./tendermint.test:/data/tendermint
{{- end}}
{{- if eq $store "fabricstore" }}
  peer0.org1.example.com:
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE={{input "name"}}test_default
{{- end}}
{{- range $i, $fossilizer := $fossilizers}}
  {{$fossilizer}}:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
    ports:
    - "{{(add 6000 $i)}}"
{{- end}}
networks:
  default:
    driver: bridge
    driver_opts:
        name: {{input "name"}}_test
