{{- $store := (input "developmentStore") -}}
{{- $fossilizers := (input "developmentFossilizer") -}}
version: '2'
services:
  agent:
    build:
      context: ./agent
    image: {{input "dockerorg"}}/{{input "name"}}-agent-js
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    volumes:
    - ./agent:/src/server
    depends_on:
    - store
{{- range $i, $fossilizer := $fossilizers}}
    - {{$fossilizer}}
{{- end}}
  store:
    image: {{index . $store}}
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
{{- if eq $store "tmstore" }}
    command: [tmstore, -endpoint, "tcp://tmapp:46657"]
    depends_on:
    - tmapp
{{- end}}
{{- if eq $store "fabricstore" }}
    user: root
    environment:
      - CLIENT_CONFIG_PATH=/var/stratumn/fabricstore/client-config.yaml
      - CHANNEL_ID=mychannel
      - CHAINCODE_ID=pop
    volumes:
      - ./fabric/crypto-config:/var/stratumn/fabricstore/crypto-config
      - ./fabric/client-config/client-config.yaml:/var/stratumn/fabricstore/client-config.yaml
{{- end}}
{{- if eq $store "postgresstore" }}
    depends_on:
    - postgres
{{- end}}
{{- if eq $store "rethinkstore" }}
    depends_on:
    - rethinkdb
{{- end}}
{{- if eq $store "postgresstore" }}
  postgres:
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    image: {{.postgres}}
{{- end}}
{{- if eq $store "rethinkstore" }}
  rethinkdb:
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    image: {{.rethink}}
{{- end}}
{{- if eq $store "tmstore" }}
  tmapp:
    image: {{.filetmpop}}
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    command: [filetmpop, -home, "/data/tendermint"]
    volumes:
    - ./validation:/data/validation
{{- end}}
{{- if eq $store "fabricstore" }}
  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: fabric/docker-compose.yml
      service: orderer.example.com
  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file: fabric/docker-compose.yml
      service: peer0.org1.example.com
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE={{input "name"}}_default
    depends_on:
      - orderer.example.com
      - couchdb0
  couchdb0:
    container_name: couchdb0
    extends:
      file: fabric/docker-compose.yml
      service: couchdb0
  cli:
    container_name: cli
    extends:
      file: fabric/docker-compose.yml
      service: cli
    depends_on:
      - orderer.example.com
      - peer0.org1.example.com
{{- end}}
{{- $root := . }}
{{- range $i, $fossilizer := $fossilizers}}
  {{$fossilizer}}:
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    image: {{index $root $fossilizer }}
    command: [{{$fossilizer}}, -http, ":{{(add 6000 $i)}}"]
{{- end}}
