{{- $store := (input "developmentStore") -}}
{{- $fossilizers := (input "developmentFossilizer") -}}
{{- $require_tmstore := (or (eq $store "filetmpop") (eq $store "dummytmpop") (eq $store "postgrestmpop") (eq $store "rethinktmpop")) -}}
version: '2'
services:
  agent:
    build:
      dockerfile: Dockerfile.test
    env_file:
    - ./config/test.env
    - ./config/test.secret.env
  store:
    env_file:
    - ./config/test.env
    - ./config/test.secret.env
{{- if eq $store "postgresstore" }}
  postgres:
    env_file:
    - ./config/test.env
    - ./config/test.secret.env
{{- end}}
{{- if eq $store "rethinkstore" }}
  rethinkdb:
    env_file:
    - ./config/test.env
    - ./config/test.secret.env
{{- end}}
{{- if $require_tmstore }}
  tmnode:
    user: root
    env_file:
    - ./config/test.env
    - ./config/test.secret.env
    volumes:
    - ./tendermint.test:/data/tendermint
{{- end}}
{{- if eq $store "fabricstore" }}
  peer0.org1.example.com:
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE={{input "name"}}test_default
{{- end}}
{{- range $i, $fossilizer := $fossilizers}}
  {{$fossilizer}}:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
    ports:
    - "{{(add 6000 $i)}}"
{{- end}}
networks:
  default:
    driver: bridge
    driver_opts:
        name: {{input "name"}}_test
