{{- with $store := (input "developmentStore") -}}
version: '2'
services:
  ui:
    image: stratumn/agent-ui:v0.2.0
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    - ./config/dev.env
    - ./config/dev.secret.env
    ports:
    - "4000:4000"
    depends_on:
    - agent
  agent:
    build:
      dockerfile: Dockerfile.dev
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
    ports:
    - "3000:3000"
  store:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
{{- if eq $store "stratumn/filestore:0.0.2-dev" }}
    volumes:
    - ./segments:/var/stratumn/filestore
{{- end}}
{{- if eq $store "stratumn/postgresstore:0.0.1-dev" }}
  postgres:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
{{- end}}
{{- if eq $store "stratumn/rethinkstore:0.0.1-dev" }}
  rethinkdb:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
{{- end}}
  fossilizer:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
networks:
  default:
    driver: bridge
    driver_opts:
        name: {{input "name"}}_dev
{{- end}}
