{{- with $store := (input "developmentStore") -}}
{{- with $fossilizer := (input "developmentFossilizer") -}}
version: '2'
env_file:
-./config/common.env
services:
  agent:
    build: .
    volumes:
    - .:/src/server
    depends_on:
    - store
    - fossilizer
  store:
    image: {{$store}}
{{- if eq $store "stratumn/postgresstore" }}
    depends_on:
    - postgres
{{- end}}
{{- if eq $store "stratumn/rethinkstore" }}
    depends_on:
    - rethinkdb
{{- end}}
{{- if eq $store "stratumn/postgresstore" }}
  postgres:
    image: postgres
{{- end}}
{{- if eq $store "stratumn/rethinkstore" }}
  rethinkdb:
    image: rethinkdb
{{- end}}
  fossilizer:
    image: {{$fossilizer}}
{{- if eq $fossilizer "stratumn/btcfossilizer" }}
    command: btcfossilizer -wif {{input "developmentFossilizerWIF"}}
{{- end}}
{{- end}}
{{- end}}
