{{- $store := (input "developmentStore") -}}
{{- $fossilizers := (input "developmentFossilizer") -}}
{{- $require_tmstore := (eq $store "tmstore") -}}
{{- $require_postgresql := (eq $store "postgresstore") -}}
{{- $require_rethinkdb := (eq $store "rethinkstore") -}}
{{- $require_couchdb := (eq $store "couchstore") -}}
version: '3'
services:
  agentui:
    image: {{.agentui}}
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    - ./config/dev.env
    - ./config/dev.secret.env
    ports:
    - "4000:4000"
{{- if $require_tmstore }}
  tmpopexplorer:
    image: {{.tmpopexplorer}}
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    - ./config/dev.env
    - ./config/dev.secret.env
    ports:
    - "8000:4000"
{{- end}}
  agent:
    build:
      dockerfile: Dockerfile.dev
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
    ports:
    - "3000:3000"
  store:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
{{- if eq $store "filestore" }}
    user: root
    volumes:
    - ./segments:/var/stratumn/filestore
{{- end}}
{{- if eq $store "fabricstore" }}
  peer0.org1.example.com:
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE={{input "name"}}dev_default
{{- end}}
{{- /* Ugly if cascade and DRY */}}
{{- /* https://github.com/stratumn/generators/issues/31 */}}
{{- if $require_postgresql }}
  postgres:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
{{- else if $require_tmstore }}
{{- if eq (input "tmpopUnderlyingStore") "postgrestmpop" }}
  postgres:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
{{- end}}
{{- end}}
{{- if $require_rethinkdb }}
  rethinkdb:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
{{- else if $require_tmstore }}
{{- if eq (input "tmpopUnderlyingStore") "rethinktmpop" }}
  rethinkdb:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
{{- end}}
{{- end}}
{{- /* End of ugly if cascade and DRY */}}
{{- if $require_couchdb }}
  couchdb:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
{{- end}}
{{- if $require_tmstore }}
  tmnode:
    user: root
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
    ports:
    - "46656-46657:46656-46657"
    volumes:
    - ./tendermint:/data/tendermint
{{- if eq (input "tmpopUnderlyingStore") "filetmstore" }}
    - ./segments:/var/stratumn/filestore
{{- end}}
{{- end}}
{{- range $i, $fossilizer := $fossilizers}}
  {{$fossilizer}}:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
    ports:
    - "{{(add 6000 $i)}}"
{{- end}}
  prometheus:
    user: root
networks:
  default:
    driver: bridge
    driver_opts:
        name: {{input "name"}}_dev
