{{- with $store := (input "developmentStore") -}}
version: '2'
env_file:
-./config/dev.env
-./config/dev.secret.env
services:
  ui:
    image: stratumn/agent-ui
    ports:
    - "4000:4000"
    depends_on:
    - agent
  agent:
    environment:
      STRATUMN_SALT: ${STRATUMN_SALT}
    ports:
    - "3000:3000"
  store:
{{- if eq $store "stratumn/filestore" }}
    volumes:
    - ./segments:/var/filestore
{{- end}}
{{- if eq $store "stratumn/postgresstore" }}
  postgres:
    volumes:
    - postgres:/var/lib/postgresql/data
{{- end}}
{{- if eq $store "stratumn/rethinkstore" }}
  rethinkdb:
    volumes:
    - rethinkdb:/data
{{- end}}
{{- if eq $store "stratumn/postgresstore" }}
volumes:
  postgres:
    driver: local
{{- end}}
{{- if eq $store "stratumn/rethinkstore" }}
volumes:
  rethinkdb:
    driver: local
{{- end}}
networks:
  default:
    driver: bridge
    driver_opts:
        name: {{input "name"}}_dev
{{- end}}
