{{- $store := (input "developmentStore") -}}
{{- $fossilizers := (input "developmentFossilizer") -}}
{{- $require_tmstore := (or (eq $store "filetmpop") (eq $store "dummytmpop") (eq $store "postgrestmpop") (eq $store "rethinktmpop")) -}}
{{- $require_postgresql := (or (eq $store "postgresstore") (eq $store "postgrestmpop")) -}}
{{- $require_rethinkdb := (or (eq $store "rethinkstore") (eq $store "rethinktmpop")) -}}
{{- $require_couchdb := (or (eq $store "fabricstore") (eq $store "couchstore")) -}}
version: '2'
services:
  agent:
    build:
      context: ./agent
    image: {{input "dockerorg"}}/{{input "name"}}-agent-js
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    volumes:
    - ./agent:/src/server
    depends_on:
    - store
{{- range $i, $fossilizer := $fossilizers}}
    - {{$fossilizer}}
{{- end}}
  store:
{{- if $require_tmstore }}
    image: {{index . "tmstore"}}
{{- else}}
    image: {{index . $store}}
{{- end}}
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
{{- if $require_tmstore }}
    command: [tmstore, -endpoint, "tcp://tmnode:46657"]
    depends_on:
    - tmnode
{{- else if eq $store "couchstore"}}
    command: [{{$store}}, -endpoint, "http://couchdb:5986"]
{{- end}}
{{- if eq $store "fabricstore" }}
    user: root
    environment:
      - CLIENT_CONFIG_PATH=/var/stratumn/fabricstore/client-config.yaml
      - CHANNEL_ID=mychannel
      - CHAINCODE_ID=pop
    volumes:
      - ./fabric/crypto-config:/var/stratumn/fabricstore/crypto-config
      - ./fabric/client-config/client-config.yaml:/var/stratumn/fabricstore/client-config.yaml
{{- end}}
{{- if $require_postgresql }}
    depends_on:
    - postgres
{{- else if $require_rethinkdb }}
    depends_on:
    - rethinkdb
{{- else if $require_couchdb }}
    depends_on:
    - couchdb
{{- end}}
{{- if $require_postgresql }}
  postgres:
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    image: {{.postgres}}
{{- else if $require_rethinkdb }}
  rethinkdb:
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    image: {{.rethinkdb}}
{{- else if $require_couchdb }}
  couchdb:
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    image: {{.couchdb}}
{{- end}}
{{- if $require_tmstore }}
  tmnode:
    image: {{index . $store}}
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    command: [{{$store}}, -home, "/data/tendermint"]
    volumes:
    - ./validation:/data/validation
{{- end}}
{{- if eq $store "fabricstore" }}
  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: fabric/docker-compose.yml
      service: orderer.example.com
  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file: fabric/docker-compose.yml
      service: peer0.org1.example.com
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE={{input "name"}}_default
    depends_on:
      - orderer.example.com
      - couchdb0
  couchdb0:
    container_name: couchdb0
    extends:
      file: fabric/docker-compose.yml
      service: couchdb0
  cli:
    container_name: cli
    extends:
      file: fabric/docker-compose.yml
      service: cli
    depends_on:
      - orderer.example.com
      - peer0.org1.example.com
{{- end}}
{{- $root := . }}
{{- range $i, $fossilizer := $fossilizers}}
  {{$fossilizer}}:
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    image: {{index $root $fossilizer }}
    command: [{{$fossilizer}}, -http, ":{{(add 6000 $i)}}"]
{{- end}}
