{{- $tmstore := (input "tmpopUnderlyingStore") -}}
{{- $require_postgresql := (eq $tmstore "postgrestmpop") -}}
{{- $require_rethinkdb := (eq $tmstore "rethinktmpop") -}}
{{- $fossilizers := (input "developmentFossilizer") -}}
{{- $clusterSize := (input "clusterSize") -}}
version: '3'
services:
  dial:
    build:
      context: ./dial
    image: {{input "dockerorg"}}/dial_seeds:latest
    depends_on:
{{- range $i, $_ := loop 0 $clusterSize}}
    - tmapp{{(add 1 $i)}}
{{- end}}
  agent:
    image: {{.agentsample}}
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    depends_on:
{{- range $i, $_ := loop 0 $clusterSize}}
{{- $node := add 1 $i}}
    - store{{$node}}
    - tmapp{{$node}}
{{- end}}
{{- range $i, $fossilizer := $fossilizers}}
    - {{$fossilizer}}
{{- end}}
{{- $tmstoreimage := index . $tmstore}}
{{- range $i, $_ := loop 0 $clusterSize}}
{{- $node := add 1 $i}}
  store{{$node}}:
    image: {{.tmstore}}
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    command: [tmstore, -endpoint, "tcp://tmapp{{$node}}:46657"]
    depends_on:
    - tmapp{{$node}}
{{- if $require_postgresql }}
    - postgres
{{- else if $require_rethinkdb }}
    - rethinkdb
{{- end}}
{{- if $require_postgresql }}
  postgres:
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    image: {{.postgres}}
{{- end}}
{{- if $require_rethinkdb }}
  rethinkdb:
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    image: {{.rethinkdb}}
{{- end}}
  tmapp{{$node}}:
    image: {{$tmstoreimage}}
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    # TODO: I need to inject rethink / postgres url here (and have one per node in the cluster)
    command: [{{$tmstore}}, -home, "/data/tendermint", "-create_empty_blocks=false", "-unsafe"]
    volumes:
    - ./validation:/data/validation
{{- end}}
{{- $root := . }}
{{- range $i, $fossilizer := $fossilizers}}
  {{$fossilizer}}:
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    image: {{index $root $fossilizer }}
    command: [{{$fossilizer}}, -http, ":{{(add 6000 $i)}}"]
{{- end}}
