{
 "title": "Indigo Store",
 "description": "Monitor your Indigo Store",
 "tags": [ "indigo, http, store, database" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP Request Count",
   "type": "graph",
   "description": "Number of store requests per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(opencensus_opencensus_io_http_server_request_count[1m])",
     "legendFormat": "All"
    },
    {
     "expr": "rate(opencensus_opencensus_io_http_server_request_count_by_method{http_method=\"GET\"}[1m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(opencensus_opencensus_io_http_server_request_count_by_method{http_method=\"POST\"}[1m])",
     "legendFormat": "POST"
    }
   ]
  },
  {
   "title": "HTTP Response Count",
   "type": "graph",
   "description": "Number of store responses per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(opencensus_opencensus_io_http_server_response_count_by_status_code{http_status=\"200\"}[1m])",
     "legendFormat": "Ok"
    },
    {
     "expr": "rate(opencensus_opencensus_io_http_server_response_count_by_status_code{http_status=\"301\"}[1m])",
     "legendFormat": "Moved"
    },
    {
     "expr": "rate(opencensus_opencensus_io_http_server_response_count_by_status_code{http_status=\"400\"}[1m])",
     "legendFormat": "Bad Request"
    },
    {
     "expr": "rate(opencensus_opencensus_io_http_server_response_count_by_status_code{http_status=\"401\"}[1m])",
     "legendFormat": "Unauthorized"
    },
    {
     "expr": "rate(opencensus_opencensus_io_http_server_response_count_by_status_code{http_status=\"403\"}[1m])",
     "legendFormat": "Forbidden"
    },
    {
     "expr": "rate(opencensus_opencensus_io_http_server_response_count_by_status_code{http_status=\"404\"}[1m])",
     "legendFormat": "Not Found"
    },
    {
     "expr": "rate(opencensus_opencensus_io_http_server_response_count_by_status_code{http_status=\"500\"}[1m])",
     "legendFormat": "Internal Error"
    },
    {
     "expr": "rate(opencensus_opencensus_io_http_server_response_count_by_status_code{http_status=\"502\"}[1m])",
     "legendFormat": "Bad Gateway"
    },
    {
     "expr": "rate(opencensus_opencensus_io_http_server_response_count_by_status_code{http_status=\"503\"}[1m])",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "Response Latency",
   "type": "graph",
   "description": "Latency in milliseconds",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(opencensus_opencensus_io_http_server_latency_bucket{le=\"1\"}[1m])",
     "legendFormat": "<= 1ms"
    },
    {
     "expr": "rate(opencensus_opencensus_io_http_server_latency_bucket{le=\"100\"}[1m])",
     "legendFormat": "<= 100ms"
    },
    {
     "expr": "rate(opencensus_opencensus_io_http_server_latency_bucket{le=\"1000\"}[1m])",
     "legendFormat": "<= 1s"
    },
    {
     "expr": "rate(opencensus_opencensus_io_http_server_latency_bucket{le=\"2000\"}[1m])",
     "legendFormat": "<= 2s"
    },
    {
     "expr": "rate(opencensus_opencensus_io_http_server_latency_bucket{le=\"10000\"}[1m])",
     "legendFormat": "<= 10s"
    }
   ]
  },
  {
   "title": "HTTP Request Size",
   "type": "graph",
   "description": "Size (in bytes) of incoming requests",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(opencensus_opencensus_io_http_server_request_bytes_bucket{le=\"+Inf\"}[1m])",
     "legendFormat": "All"
    },
    {
     "expr": "rate(opencensus_opencensus_io_http_server_request_bytes_bucket{le=\"1024\"}[1m])",
     "legendFormat": "<= 1kB"
    },
    {
     "expr": "rate(opencensus_opencensus_io_http_server_request_bytes_bucket{le=\"4096\"}[1m])",
     "legendFormat": "<= 4kB"
    },
    {
     "expr": "rate(opencensus_opencensus_io_http_server_request_bytes_bucket{le=\"65536\"}[1m])",
     "legendFormat": "<= 64kB"
    }
   ]
  },
  {
   "title": "HTTP Response Size",
   "type": "graph",
   "description": "Size (in bytes) of outgoing responses",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(opencensus_opencensus_io_http_server_response_bytes_bucket{le=\"+Inf\"}[1m])",
     "legendFormat": "All"
    },
    {
     "expr": "rate(opencensus_opencensus_io_http_server_response_bytes_bucket{le=\"1024\"}[1m])",
     "legendFormat": "<= 1kB"
    },
    {
     "expr": "rate(opencensus_opencensus_io_http_server_response_bytes_bucket{le=\"4096\"}[1m])",
     "legendFormat": "<= 4kB"
    },
    {
     "expr": "rate(opencensus_opencensus_io_http_server_response_bytes_bucket{le=\"65536\"}[1m])",
     "legendFormat": "<= 64kB"
    }
   ]
  }
 ]
}