{
 "title": "Indigo Tendermint Node",
 "description": "Monitor your Indigo Tendermint Node",
 "tags": [ "indigo, tendermint, blockchain" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Block Production Rate",
   "type": "singlestat",
   "description": "Number of blocks produced per second",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(opencensus_block_count[5m])",
     "legendFormat": "blocks/sec"
    }
   ]
  },
  {
   "title": "Blockchain Height",
   "type": "singlestat",
   "description": "Height of the last block produced",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "opencensus_block_count" }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "description": "Number of transactions",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(opencensus_tx_count{tx_status=\"valid\"}[1m])",
     "legendFormat": "valid txs"
    },
    {
     "expr": "rate(opencensus_tx_count{tx_status=\"invalid\"}[1m])",
     "legendFormat": "invalid txs"
    }
   ]
  },
  {
   "title": "Transactions per block",
   "type": "graph",
   "description": "Number of transactions per block",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(opencensus_tx_per_block_bucket{le=\"1\"}[1m])",
     "legendFormat": "empty blocks"
    },
    {
     "expr": "rate(opencensus_tx_per_block_bucket{le=\"5\"}[1m])",
     "legendFormat": "0 < tx/block <= 5"
    },
    {
     "expr": "rate(opencensus_tx_per_block_bucket{le=\"10\"}[1m])",
     "legendFormat": "5 < tx/block <= 10"
    },
    {
     "expr": "rate(opencensus_tx_per_block_bucket{le=\"50\"}[1m])",
     "legendFormat": "10 < tx/block <= 50"
    },
    {
     "expr": "rate(opencensus_tx_per_block_bucket{le=\"100\"}[1m])",
     "legendFormat": "50 < tx/block <= 100"
    }
   ]
  }
 ]
}