{{- $store := (input "developmentStore") -}}
{{- $fossilizer := (input "developmentFossilizer") -}}
version: '2'
services:
  agentui:
    image: {{.agentui}}
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    - ./config/dev.env
    - ./config/dev.secret.env
    ports:
    - "4000:4000"
{{- if eq $store "tmstore" }}
  indigoexplorer:
    image: {{.indigoexplorer}}
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    - ./config/dev.env
    - ./config/dev.secret.env
    ports:
    - "8000:4000"
{{- end}}
  agent:
    build:
      dockerfile: Dockerfile.dev
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
    ports:
    - "3000:3000"
  store:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
{{- if eq $store "filestore" }}
    user: root
    volumes:
    - ./segments:/var/stratumn/filestore
{{- end}}
{{- if eq $store "postgresstore" }}
  postgres:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
{{- end}}
{{- if eq $store "rethinkstore" }}
  rethinkdb:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
{{- end}}
{{- if eq $store "tmstore" }}
  tmapp:
    user: root
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
    ports:
    - "46656-46657:46656-46657"
    volumes:
    - ./tendermint:/data/tendermint
    - ./validation:/data/validation
    - ./segments:/var/stratumn/filestore
{{- end}}
{{- if ne $fossilizer "none" }}
  fossilizer:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
{{- end}}
networks:
  default:
    driver: bridge
    driver_opts:
        name: {{input "name"}}_dev
