{{- $store := (input "developmentStore") -}}
{{- $fossilizer := (input "developmentFossilizer") -}}
version: '2'
services:
  agent:
    build:
      dockerfile: Dockerfile.test
    env_file:
    - ./config/test.env
    - ./config/test.secret.env
  store:
    env_file:
    - ./config/test.env
    - ./config/test.secret.env
{{- if eq $store "postgresstore" }}
  postgres:
    env_file:
    - ./config/test.env
    - ./config/test.secret.env
{{- end}}
{{- if eq $store "rethinkstore" }}
  rethinkdb:
    env_file:
    - ./config/test.env
    - ./config/test.secret.env
{{- end}}
{{- if eq $store "tmstore" }}
  tmapp:
    user: root
    env_file:
    - ./config/test.env
    - ./config/test.secret.env
    volumes:
    - ./tendermint.test:/data/tendermint
{{- end}}
{{- if ne $fossilizer "none" }}
  fossilizer:
    env_file:
    - ./config/test.env
    - ./config/test.secret.env
{{- end}}
networks:
  default:
    driver: bridge
    driver_opts:
        name: {{input "name"}}_test
